apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: pokeapi-app
  name: pokeapi-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi