version: '2.4'
services:
  cache:
    image: redis:alpine
    volumes:
      - redis_data:/data

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'pokemon'
      POSTGRES_USER: 'ash'
      POSTGRES_DB: 'pokeapi'
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: ./Resources/docker/app/Dockerfile
    image: nvanderhoeven/pokeapi_app
    volumes:
      - .:/code
    links:
      - db
      - cache
    depends_on:
      - db
      - cache

  web:
    build: 
      context: ./Resources
      dockerfile: ./docker/web/Dockerfile
    image: nvanderhoeven/pokeapi_web
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - app:ro
    links:
      - app

volumes:
  pg_data:
  redis_data:
